### ISSUE TITLE
New tag on double-clicking to run Python scripts

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/meta#224] opened 2023-08-31 09:32 UTC
### Tag Name

double-click-to-run

### What kind of content should the tag include?

A common question from beginners just starting out is "Why does my program instantly close when I open them?", which occurs because they double-click a Python script to run it rather than running it from a command line or IDE.

This tag could explain this behavior and contain instructions on how to run the script from a command line instead.

I also considered including the quick and dirty solution of appending `input()` to the script, but decided against it as it is just a workaround that does not solve the issue.

**Comment by wookie184** [comment] 2023-08-31 11:19
It might be hard to explain the correct alternative since the exact solution is dependant on a few things (e.g. OS, or editor/IDE), and instructions would depend on the users familiarity with a few things (e.g. do they even know what a command line is).

It could still be useful to explain why it's not the correct way of running things, and say what the correct way is but leaving the details to be explained by whoever invoked the tag or linking to an external resources.

**Comment by wookie184** [comment] 2023-08-31 11:59
Just noticed this is a duplicate of #206, lets move there

**Closed as not planned by wookie184** 2023-08-31 11:59 UTC
Labels: meta: duplicate, status: actionable, area: tags
